version: '3.8'

services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - '27017:27017'
    restart: unless-stopped
    networks:
      - custom
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 2

  fastapi_uvicorn:
    build: .
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - .:/one-time-secret
    command: sh -c "uvicorn run:my_app --reload --host 0.0.0.0 --port 8000"
    networks:
      - custom

networks:
  custom:






