version: '3.8'

services:
  fastapi_uvicorn:
    build: .
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - .:/one-time-secret
    command: sh -c "uvicorn run:my_app --reload --host 0.0.0.0 --port 8000"

